## 1. Import required Libraries

In [ ]:
from pathlib import Path

import pandas as pd
import numpy as np

from sklearn.metrics import roc_auc_score, f1_score

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

SEED = 983
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

## 2. Import data

In [27]:
curr_path = Path.cwd()
Output_Datasets_path = curr_path.parent.parent / 'Output_Datasets'

In [28]:
X_train_clean_path = Output_Datasets_path / 'X_train_clean.npy'
Y_train_clean_path = Output_Datasets_path / 'Y_train_clean.npy'
X_val_clean_path = Output_Datasets_path / 'X_val_clean.npy'
Y_val_clean_path = Output_Datasets_path / 'Y_val_clean.npy'

In [29]:
print("Loading X_train_clean...")
X_train_clean = np.load(X_train_clean_path, allow_pickle=True)
print("Loading Y_train_clean...")
Y_train_clean = np.load(Y_train_clean_path, allow_pickle=True)
print("Successfully loaded X_train_clean and Y_train_clean")

Loading X_train_clean and Y_train_clean...
Successfully loaded X_train_clean and Y_train_clean


In [30]:
# print("Loading X_val_clean and Y_val_clean...")
# X_val_clean = np.load(X_val_clean_path, allow_pickle=True)
# Y_val_clean = np.load(Y_val_clean_path, allow_pickle=True)
# print("Successfully loaded X_val_clean and Y_val_clean")

In [31]:
print(f'Shape of X_train_clean: {X_train_clean.shape}')
#print(f'Shape of X_val_clean: {X_val_clean.shape}')

Shape of X_train_clean: (17090, 1000, 12)


In [32]:
print(f'Shape of Y_train_clean: {Y_train_clean.shape}')
#print(f'Shape of Y_val_clean: {Y_val_clean.shape}')

Shape of Y_train_clean: (17090, 5)


In [33]:
print(Y_train_clean[0])
print(Y_train_clean[290])

[0 0 0 1 0]
[1 0 0 0 0]


In [34]:
X_train_clean[0].shape

(1000, 12)

## 3. PyTorch DataSet 

In [35]:
class EcgDataset(Dataset):
    def __init__(self, inputs, target):
        self.inputs = inputs
        self.target = target

    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, idx):
        return torch.tensor(self.inputs[idx], dtype=torch.float32), torch.tensor(self.target[idx], dtype=torch.float32)

In [36]:
print('Preparing dataset...')
train_dataset = EcgDataset(inputs=X_train_clean, target=Y_train_clean)
# val_dataset = EcgDataset(X_val_clean, Y_val_clean)
print('Completed dataset preparation!')

Preparing dataset...
Completed dataset preparation!


In [37]:
X_train_clean[0]

array([[-0.7290525 , -0.3258207 ,  0.38159752, ..., -0.0825962 ,
        -0.13979171, -0.27320004],
       [-0.71040192, -0.30146305,  0.387582  , ..., -0.09935392,
        -0.12149178, -0.25536681],
       [-0.73526937, -0.25883717,  0.45341134, ..., -0.08929929,
        -0.10319185, -0.23753358],
       ...,
       [ 0.43971742,  0.00909697, -0.41433899, ...,  0.08498095,
        -0.14711168, -0.19830048],
       [ 0.54540406,  0.03345462, -0.48615281, ...,  0.81561734,
        -0.1654116 , -0.3409663 ],
       [ 0.14752494, -0.17967481, -0.32457172, ...,  0.48381457,
        -0.12515176, -0.41943251]])

In [38]:
X_train_clean[0].shape

(1000, 12)

## 4. PyTorch Dataloader

In [ ]:
BATCH_SIZE = 50

In [40]:
train_dataloader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
# val_dataloader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=True)

In [41]:
for i, x in enumerate(train_dataloader):
    if i == 2:
        break
    print(x[0])
    print(x[1])

tensor([[[ 6.2622e-01,  1.9178e-01, -4.1434e-01,  ...,  6.0112e-01,
           5.0071e-01,  3.7236e-01],
         [ 1.4966e+00,  1.8785e+00,  4.0554e-01,  ...,  2.0222e+00,
           1.7231e+00,  1.3140e+00],
         [ 2.5970e+00,  4.6979e+00,  2.1171e+00,  ...,  4.1906e+00,
           3.5531e+00,  2.7442e+00],
         ...,
         [-2.1305e-01, -2.1621e-01, -7.3940e-03,  ..., -1.3957e-01,
          -8.4892e-02, -1.0913e-01],
         [-2.6900e-01, -2.3448e-01,  2.8513e-02,  ..., -1.4628e-01,
          -1.5809e-01, -1.1983e-01],
         [-2.3170e-01, -1.8576e-01,  4.0482e-02,  ..., -1.1276e-01,
          -7.3912e-02, -5.5635e-02]],

        [[-1.1358e-01, -1.1269e-01, -1.4095e-03,  ...,  5.1466e-02,
          -2.1665e-01, -2.2327e-01],
         [-1.2602e-01, -1.3096e-01, -1.4095e-03,  ...,  3.1356e-02,
          -2.1665e-01, -2.2327e-01],
         [-2.6279e-01, -2.8319e-01, -3.1332e-02,  ..., -2.1592e-03,
          -2.2031e-01, -2.2683e-01],
         ...,
         [-2.6279e-01, -2

## 5. CNN Model

In [42]:
def CNN():
    super().__init__()
    pass

## 4. Bidirectional LSTM Model

In [43]:
SIGNAL_SIZE = 12 #1000 (sequentially for a single electrode)
NUM_LAYERS = 2
OUTPUT_DIM = 5
HIDDEN_DIM = 90
EMBED_DIM = 126
DROPOUT = 0.2

In [44]:
class BiLSTM(nn.Module):
    def __init__(self, input_dim=SIGNAL_SIZE, hidden_dim=HIDDEN_DIM, embed_dim=EMBED_DIM, output_dim=OUTPUT_DIM, num_layers=NUM_LAYERS, dropout=0.25):
        super(BiLSTM, self).__init__()
        
        # self.embedding = nn.Embedding(signal_size, embed_dim, padding_idx=0)
        self.proj = nn.Linear(input_dim, embed_dim)
        self.lstm = nn.LSTM(
                    input_size=embed_dim,
                    hidden_size=hidden_dim,
                    num_layers=NUM_LAYERS,
                    batch_first=True,
                    bias=True,
                    dropout=dropout if num_layers>1 else 0,
                    bidirectional=True
        )
        self.fc = nn.Linear(hidden_dim*2, output_dim)
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, signal):
        # embedded = self.dropout(self.embedding(signal)) # [batch_size, max_len, embed_dim]
        projected = self.dropout(torch.relu(self.proj(signal)))
        
        lstm_out, (hidden, cell) = self.lstm(projected)
        
        # concatenate forward and backward final hidden state
        hidden_last = torch.cat((hidden[-2, :, :], hidden[-1, :, :]), dim=1)    # [batch_size, hidden_dim*2]
        logits = self.fc(self.dropout(hidden_last))
        
        return logits        

In [45]:
lstmModel = BiLSTM(input_dim=SIGNAL_SIZE,
                   embed_dim=EMBED_DIM,
                   hidden_dim=HIDDEN_DIM,
                   output_dim=OUTPUT_DIM,
                   num_layers=NUM_LAYERS,
                   dropout=DROPOUT)
print(lstmModel)

BiLSTM(
  (proj): Linear(in_features=12, out_features=126, bias=True)
  (lstm): LSTM(126, 90, num_layers=2, batch_first=True, dropout=0.2, bidirectional=True)
  (fc): Linear(in_features=180, out_features=5, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)


## 5. CNN and LSTM Hybrid Model

In [46]:
def hybrid(CNN_Model, BiLTM_Model):
    pass

## 6. Training

### 6.1 Bi-LSTM Training

In [47]:
LEARNING_RATE = 1e-3
EPOTCHS = 5

In [48]:
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.AdamW(lstmModel.parameters(), lr = LEARNING_RATE)

In [ ]:
def train_lstm_model(model, datasetloader, criterion, optimizer, device):
    model.to(device)
    model.train()
    train_loss, total_samples, total_elememts = 0, 0, 0
    correct_exact, correct_elements = 0, 0
    
    
    for x_batch, y_batch in datasetloader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)

        optimizer.zero_grad()
        logits = model(x_batch)
        loss = criterion(logits, y_batch)

        loss.backward()
        optimizer.step()


        probs = torch.sigmoid(logits)
        preds = (probs > 0.6).float()

        exact_matches = (preds == y_batch).all(dim=1)

        correct_exact += exact_matches.sum().item()
        correct_elements += (preds == y_batch).sum().item()

        total_samples += y_batch.shape[0]
        total_elememts += y_batch.numel()
        train_loss += loss.item() * y_batch.shape[0]

    avg_train_loss = train_loss / total_samples
    exect_acc = correct_exact / total_samples
    element_acc = correct_elements / total_elememts

    return avg_train_loss, exect_acc, element_acc

In [50]:
print('Training model....')
for epoch in range(1, EPOTCHS+1):

    train_loss, exect_train_accuracy, element_wise_train_acc = train_lstm_model(lstmModel, train_dataloader, criterion, optimizer, device)

    # test_loss, test_accuracy = evaluate_model(lstmModel, test_loader, criterion, device)

    # print(f'Epoch [{epoch}/{EPOTCHS}] | Train Loss: {train_loss:.3f} | Train Acc: {train_accuracy*100:.3f}% | Test Loss: {test_loss:.3f} | Test Acc: {test_accuracy*100:.3f}%')

    print(f'Epoch [{epoch}/{EPOTCHS}] | Train Loss: {train_loss:.3f} | Exect Train Acc: {exect_train_accuracy*100:.f}% | Element Wise Train Loss: {element_wise_train_acc*100:.3f}%')

Training model....
Epoch [1/5] | Train Loss: 0.534 | Exect Train Acc: 7.841% | Element Wise Train Loss: 0.749
Epoch [2/5] | Train Loss: 0.516 | Exect Train Acc: 12.791% | Element Wise Train Loss: 0.756
Epoch [3/5] | Train Loss: 0.483 | Exect Train Acc: 22.440% | Element Wise Train Loss: 0.768
Epoch [4/5] | Train Loss: 0.485 | Exect Train Acc: 23.774% | Element Wise Train Loss: 0.770
Epoch [5/5] | Train Loss: 0.495 | Exect Train Acc: 15.758% | Element Wise Train Loss: 0.759


```
Training model....
Epoch [1/5] | Train Loss: 0.534 | Exect Train Acc: 7.841% | Element Wise Train Loss: 0.749
Epoch [2/5] | Train Loss: 0.516 | Exect Train Acc: 12.791% | Element Wise Train Loss: 0.756
Epoch [3/5] | Train Loss: 0.483 | Exect Train Acc: 22.440% | Element Wise Train Loss: 0.768
Epoch [4/5] | Train Loss: 0.485 | Exect Train Acc: 23.774% | Element Wise Train Loss: 0.770
Epoch [5/5] | Train Loss: 0.495 | Exect Train Acc: 15.758% | Element Wise Train Loss: 0.759
```

## 7. Evaluation

## 8. Visualization